import {readFileSync,writeFileSync,mkdirSync,rmSync,cpSync,existsSync} from 'node:fs';
import {dirname} from 'node:path';
import {loadArticles,escape as e,pathFor,series} from './content.mjs';
const review=process.argv.includes('--review');
const out=process.env.OUTPUT_DIR||'dist';
if(!['dist','review-dist','test-dist','test-review-dist'].includes(out))throw new Error('Unsupported output directory');
const site=JSON.parse(readFileSync('content/site.json','utf8'));
const all=loadArticles(process.env.CONTENT_DIR||'content/articles');
const published=all.filter(a=>a.status==='published');
const visible=review?all:published;
const learning=visible.filter(a=>a.series==='explaining').sort((a,b)=>(a.order??999)-(b.order??999));
const news=visible.filter(a=>a.series==='today').sort((a,b)=>(b.publishedAt||b.draftDate).localeCompare(a.publishedAt||a.draftDate));
const fmt=v=>new Date(v+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
const url=p=>site.url+(p==='/'?'/':p);
const date=a=>a.status==='draft'?`Source draft · ${fmt(a.draftDate)}`:`<time datetime="${a.publishedAt}">${fmt(a.publishedAt)}</time>`;
const nav=(path)=>[['/explaining','Explaining'],['/today','Today'],['/projects','Projects'],['/about','About']].map(([href,label])=>`<a href="${href}"${path===href||path.startsWith(href+'/')?' aria-current="page"':''}>${label}</a>`).join('');
function page({title,description=site.description,path='/',body,article,noindex=false}){
 const draft=article?.status==='draft';
 const schema=article&&!draft?{'@context':'https://schema.org','@type':'Article',headline:title,description,author:{'@type':'Person',name:site.author},datePublished:article.publishedAt,...(article.updatedAt?{dateModified:article.updatedAt}:{}),mainEntityOfPage:url(path)}:null;
 return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · ${e(site.name)}</title><meta name="description" content="${e(description)}">${review||noindex?'<meta name="robots" content="noindex,nofollow">':''}${draft||noindex?'':`<link rel="canonical" href="${url(path)}">`}<meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${article&&!draft?'article':'website'}">${draft?'':`<meta property="og:url" content="${url(path)}">`}<meta property="og:site_name" content="Fixing Everything"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(description)}">${article&&!draft?`<meta property="article:published_time" content="${article.publishedAt}">${article.updatedAt?`<meta property="article:modified_time" content="${article.updatedAt}">`:''}`:''}<link rel="stylesheet" href="/assets/style.css"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="alternate" type="application/rss+xml" title="Fixing Everything" href="/rss.xml"><link rel="alternate" type="application/rss+xml" title="Explaining Omarchy" href="/explaining/rss.xml"><link rel="alternate" type="application/rss+xml" title="Today in Omarchy" href="/today/rss.xml">${schema?`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`:''}<script src="/assets/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>${review?'<div class="review">Private editorial preview · unpublished drafts included. <a href="/review">Review notes</a></div>':''}<div class="wrap"><div class="topline"><span>Tom Ballard on Omarchy</span><span>Independent &amp; unofficial</span></div><header class="header"><a class="brand" href="/">Fixing Everything<span aria-hidden="true">.</span></a><nav aria-label="Main navigation">${nav(path)}</nav></header><main id="main" tabindex="-1">${body}</main><footer><div class="foot"><div><p>Fixing Everything · Tom Ballard</p><p>An unofficial Omarchy publication.</p></div><nav aria-label="Elsewhere"><a href="/rss.xml">RSS</a><a href="https://x.com/tcballard">X</a><a href="https://github.com/tcballard">GitHub</a><a href="https://tcballard.dev">Tom’s website</a></nav></div></footer></div></body></html>`;
}
function emit(path,html){const dest=path==='/'?`${out}/index.html`:`${out}${path}/index.html`;mkdirSync(dirname(dest),{recursive:true});writeFileSync(dest,html);}
const row=a=>`<article class="row"><p class="meta">${date(a)}</p><h3><a href="${pathFor(a)}">${e(a.title)}</a></h3><p class="meta">${a.minutes} min read${a.status==='draft'?' · Draft':''}</p></article>`;
const projectCards=()=>`<div class="projects">${site.projects.map(p=>`<article class="project"><p class="mono category">${e(p.category)}</p><h3><a href="${e(p.url)}">${e(p.name)}</a></h3><p>${e(p.description)}</p>${p.note?`<p class="badge">${e(p.note)}</p>`:''}<a class="read-link" href="${e(p.url)}">Explore on GitHub <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
const seriesBlock=()=>`<section class="section"><div class="series-grid"><a class="series-link" href="/explaining">${existsSync('assets/explaining-omarchy-square.png')?`<img class="explain-art" src="/assets/explaining-omarchy-square.png" alt="Explaining Omarchy’s cyan geometric mark" width="1200" height="1200" loading="lazy">`:``}<p class="eyebrow">Understand your desktop</p><h2>Explaining Omarchy</h2><p>Plain explanations, one idea at a time. Find your feet, understand the choices and try things for yourself.</p><span class="read-link">Browse the explanations <span aria-hidden="true">↗</span></span></a><a class="series-link" href="/today">${existsSync('assets/today-in-omarchy.png')?`<img src="/assets/today-in-omarchy.png" alt="Fixing Everything — Today in Omarchy" width="1500" height="500" loading="lazy">`:``}<p class="eyebrow">Follow what’s changing</p><h2>Today in Omarchy</h2><p>The daily view of Omarchy’s releases, projects and community, with links to the work behind the news.</p><span class="read-link">Visit the archive <span aria-hidden="true">↗</span></span></a></div></section>`;
const intro=(label,title,description)=>`<header class="page-intro"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="intro">${description}</p></header>`;
const empty=(title,description)=>`<div class="empty"><h2>${title}</h2><p>${description}</p><a class="read-link" href="https://x.com/tcballard">Find Tom on X <span aria-hidden="true">↗</span></a></div>`;
function companion(a){if(!a.lessonId)return '';
 const actions={super:'Find the key your keyboard calls Windows or Command, then practise recognising Super.',launcher:'Open your launcher, search for an app you recognise, then close it without opening anything.',terminal:'Open or focus a terminal and leave it selected for a moment.',workspace:'Switch to another numbered workspace, then return when you are ready.',browser:'Open or focus your browser.',focus:'Switch focus between two app windows on the same workspace.',help:'Find the keyboard shortcut reference and choose one shortcut to practise.'};
 const command=`omarchy-shell shell summon io.github.tcballard.omarchy-101 '{"lesson":"${a.lessonId}"}'`;
 const install=`git clone https://github.com/tcballard/omarchy-101.git omarchy-101\ncd omarchy-101\ngit checkout ${site.companion.ref}`;
 return `<aside class="companion" aria-labelledby="try-101"><p class="eyebrow">Read it here. Try it on your desktop.</p><h2 id="try-101">Try this in 101</h2><p>${actions[a.lessonId]}</p><p><strong>Development preview:</strong> lesson-opening support is proposed in <a href="${site.companion.pullRequest}">101 PR #3</a>, which is still an open draft as checked on ${fmt(site.companion.verifiedOn)}. It requires a compatible checkout on Omarchy Quattro; this is not a released integration.</p><details><summary>Installation and compatibility</summary><p>For the exact reviewed preview source:</p><pre><code>${e(install)}</code></pre><p>Following the repository’s <a href="https://github.com/tcballard/omarchy-101/blob/${site.companion.ref}/README.md">preview installation instructions</a>, copy this checkout to <code>~/.config/omarchy/plugins/io.github.tcballard.omarchy-101/</code>, validate it and enable it. Back up an existing checkout before replacing it.</p><pre><code>omarchy plugin validate ~/.config/omarchy/plugins/io.github.tcballard.omarchy-101
omarchy-shell shell rescanPlugins
omarchy plugin enable io.github.tcballard.omarchy-101</code></pre><p>Live desktop validation is still outstanding in the proposal. You can read this explanation without installing 101.</p></details><p>Once a compatible version is installed and enabled, paste this into your terminal:</p><pre tabindex="0" aria-label="101 lesson command"><code id="lesson-command">${e(command)}</code></pre><div><button type="button" data-copy="lesson-command">Copy command</button><span role="status" aria-live="polite"></span></div><p class="meta">This command selects a lesson. It does not install 101 or complete the exercise.</p></aside>`;
}
function articlePage(a){
 const i=learning.indexOf(a);const sequence=a.series==='explaining'?learning:news;const n=sequence.indexOf(a);
 const neighbors=[sequence[n-1],sequence[n+1]];
 const rail=a.series==='explaining'?`<aside class="rail" aria-label="Learning sequence"><h2>Explaining Omarchy</h2><ol>${learning.map(b=>`<li><a href="${pathFor(b)}"${a.id===b.id?' aria-current="page"':''}>${e(b.title)}</a></li>`).join('')}</ol><p class="note">Read in order, or follow the question that brought you here.</p><a href="/explaining">All explanations</a></aside>`:`<aside class="rail"><h2>Today in Omarchy</h2><p>A daily archive of releases, projects and community news.</p><a href="/today">All editions</a></aside>`;
 const media=a.media.map(m=>`<figure><img src="${e(m.src)}" alt="${e(m.alt)}" width="${m.width}" height="${m.height}" loading="lazy">${m.caption?`<figcaption>${e(m.caption)}</figcaption>`:''}</figure>`).join('');
 const body=`<header class="article-head"><p class="eyebrow"><a href="/${a.series}">${series[a.series]}</a>${a.series==='explaining'?` / ${String(i+1).padStart(2,'0')}`:''}</p><h1>${e(a.title)}</h1><div class="meta"><span>${e(a.author)}</span><span>${date(a)}</span><span>${a.minutes} min read</span>${a.updatedAt?`<span>Updated ${fmt(a.updatedAt)}</span>`:''}</div>${a.originalXUrl?`<a class="read-link" href="${e(a.originalXUrl)}">Originally published on X <span aria-hidden="true">↗</span></a>`:''}${a.status==='draft'?'<p class="meta" style="margin-top:1rem">Unpublished source draft. Original X publication has not been verified.</p>':''}</header><div class="article-layout"><div class="prose">${a.html}${media}${companion(a)}<nav class="article-next" aria-label="Related reading">${neighbors.map((b,j)=>b?`<a href="${pathFor(b)}"><span>${j?'Next':'Previous'} ${a.series==='today'?'edition':'explanation'}</span><strong>${e(b.title)}</strong></a>`:'<span></span>').join('')}</nav></div>${rail}</div>`;
 return page({title:a.title,description:a.summary,path:pathFor(a),body,article:a});
}
rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});cpSync('assets',`${out}/assets`,{recursive:true});
writeFileSync(`${out}/favicon.svg`,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="#181923"/><path d="M8 7h18v5H13v4h10v5H13v6H8z" fill="#63c8e5"/></svg>');
const feature=review?(learning[0]||visible[0]):[...published].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt))[0];
const latest=feature?`<section class="section"><div class="section-head"><h2>${review&&feature.status==='draft'?'On the reading desk':'Latest writing'}</h2><a href="/explaining">All explanations</a></div><div class="lead-grid"><article class="feature"><div class="feature-art">${existsSync('assets/explaining-omarchy-square.png')?`<img src="/assets/explaining-omarchy-square.png" alt="" width="1200" height="1200">`:``}<p class="eyebrow">${series[feature.series]}</p></div><p class="meta">${date(feature)}</p><h2><a href="${pathFor(feature)}">${e(feature.title)}</a></h2><p class="summary">${e(feature.summary)}</p><a class="read-link" href="${pathFor(feature)}">${feature.status==='draft'?'Read the draft':'Read the explanation'} <span aria-hidden="true">↗</span></a></article><div>${visible.filter(a=>a.id!==feature.id).sort((a,b)=>(b.publishedAt||b.draftDate).localeCompare(a.publishedAt||a.draftDate)).slice(0,3).map(row).join('')}</div></div></section>`:'';
emit('/',page({title:'Omarchy, explained',body:`<section class="home-intro"><p class="eyebrow">Writing / Learning / Making</p><h1>Omarchy,<br>explained.</h1><p>I’m Tom Ballard. This is where I write about Omarchy, work out how it works, and share what I’m building along the way.</p></section>${latest}${seriesBlock()}<section class="section"><div class="section-head"><h2>Things I’m building</h2><a href="/projects">All projects</a></div>${projectCards()}</section>`}));
const topics=[...new Set(learning.flatMap(a=>a.topics))];
emit('/explaining',page({title:'Explaining Omarchy',path:'/explaining',body:intro('Learn / At your own pace','Explaining<br>Omarchy.','One idea at a time. Understand the desktop, try something small, then come back when the next question turns up.')+(learning.length?`<div class="index-head"><p class="mono" id="filter-status" role="status" style="margin:0">${learning.length} explanations${review?' · drafts for review':''}</p><label for="topic">Topic <select id="topic"><option value="all">All topics</option>${topics.map(t=>`<option value="${e(t)}">${e(t)}</option>`).join('')}</select></label></div><ol class="learning-list">${learning.map((a,i)=>`<li data-topics="${e(JSON.stringify(a.topics))}"><span class="number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><h2><a href="${pathFor(a)}">${e(a.title)}</a></h2><p>${e(a.summary)}</p></div><div class="meta">${date(a)}<br>${a.minutes} min read${a.lessonId?'<br>101 preview exercise':''}</div></li>`).join('')}</ol>`:empty('The explanations are moving in.','This will be the permanent home of Explaining Omarchy. The archive is being prepared; existing writing is still on X.'))}));
emit('/today',page({title:'Today in Omarchy',path:'/today',body:`${existsSync('assets/today-in-omarchy.png')?`<img class="today-art" src="/assets/today-in-omarchy.png" alt="Fixing Everything — Today in Omarchy" width="1500" height="500">`:``}${intro('The daily archive','Today in Omarchy.','Releases, projects and the people building them. A dated record of what changed, with the sources close at hand.')}${news.length?news.map(row).join(''):empty('The archive is on its way.','Today in Omarchy is moving here from X. Editions will appear here once the original articles and their sources have been brought across.')}<p class="mono" style="margin-top:2rem"><a href="/today/rss.xml">Subscribe to Today in Omarchy by RSS</a></p>`}));
emit('/projects',page({title:'Projects',path:'/projects',body:intro('Made with curiosity','Things I’m building.','Native applications, learning tools and resources for people making Omarchy their own.')+projectCards()+`<section class="section"><h2>Come and build with me.</h2><p>Try a project, tell me what feels off, or send a pull request. Issues and contributions are encouraged.</p><a class="read-link" href="https://github.com/tcballard">More on GitHub <span aria-hidden="true">↗</span></a></section>`}));
emit('/about',page({title:'About Tom and Fixing Everything',path:'/about',body:intro('A personal publication','Hello, I’m Tom.','I write about Omarchy and build things for it.')+`<div class="about-layout"><div><p>Fixing Everything is where I share that work: explanations of the things I’m learning, notes on what’s changing, and projects you can try or help improve.</p><p><a href="/explaining">Explaining Omarchy</a> takes one concept at a time. <a href="/today">Today in Omarchy</a> follows releases, projects and community developments.</p><p>The aim is a useful place to return to, whether you’re finding your Super key or building your next application.</p><a class="read-link" href="https://tcballard.dev">More about me <span aria-hidden="true">↗</span></a></div><aside class="about-aside"><h2>Independent.<br>Unofficial.</h2><p>This is Tom Ballard’s personal publication. It is not affiliated with or endorsed by the Omarchy project.</p><p>For official downloads and documentation, visit <a href="https://omarchy.org">omarchy.org</a>.</p><p>Found something that needs fixing? <a href="https://github.com/tcballard/fixing-everything/issues">Open an issue</a>.</p></aside></div>`}));
for(const a of visible)emit(pathFor(a),articlePage(a));
if(review)emit('/review',page({title:'Editorial review notes',path:'/review',noindex:true,body:`<div class="review-notes"><p class="eyebrow">Private preview</p><h1>Before publishing.</h1><p>${all.filter(a=>a.status==='draft').length} source drafts are available for review. Draft status is not evidence of prior publication.</p><ul><li>Confirm each article’s original X URL and publication date before changing its status. Source draft dates are not publication dates.</li><li>No complete Today in Omarchy edition was recovered. Supply the source text, X URL and original media for each edition to migrate.</li><li>101 PRs #2 and #3 remain open drafts. Commands target the specific preview checkout; no Articles.js mapping has been activated.</li><li>The intended domain is <code>omarchy.tcballard.dev</code>. This preview does not establish that the custom domain is live.</li></ul><p>Public builds omit drafts entirely. RSS and sitemaps contain only published articles, including in this private preview.</p><a href="/explaining">Review the explanations</a></div>`}));
writeFileSync(`${out}/404.html`,page({title:'Page not found',path:'/404',noindex:true,body:intro('404 / Page not found','This page isn’t here.','The link may be old, or the article may not be published yet.')+'<p><a class="read-link" href="/">Back to the publication</a></p><p><a href="/explaining">Browse explanations</a> · <a href="/today">Browse daily editions</a></p>'}));
const cdata=s=>'<![CDATA['+s.replace(/\]\]>/g,']]]]><![CDATA[>')+']]>';
function rss(items,title,path){return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><title>${e(title)}</title><link>${url(path)}</link><description>${e(site.description)}</description><language>en-GB</language><atom:link href="${url(path==='/'?'/rss.xml':path+'/rss.xml')}" rel="self" type="application/rss+xml"/>${items.sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).map(a=>`<item><title>${e(a.title)}</title><link>${url(pathFor(a))}</link><guid isPermaLink="false">${e(a.id)}</guid><pubDate>${new Date(a.publishedAt).toUTCString()}</pubDate><description>${e(a.summary)}</description><content:encoded>${cdata(a.html.replace(/(href|src)="\/(?!\/)/g,`$1="${site.url}/`))}</content:encoded></item>`).join('')}</channel></rss>`;}
writeFileSync(`${out}/rss.xml`,rss([...published],site.name,'/'));
for(const name of ['explaining','today'])writeFileSync(`${out}/${name}/rss.xml`,rss(published.filter(a=>a.series===name),series[name],'/'+name));
const paths=['/','/explaining','/today','/projects','/about',...published.map(pathFor)];
writeFileSync(`${out}/sitemap.xml`,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${url(p)}</loc></url>`).join('')}</urlset>`);
writeFileSync(`${out}/robots.txt`,review?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
writeFileSync(`${out}/.nojekyll`,'');
writeFileSync(`${out}/build-manifest.json`,JSON.stringify({mode:review?'private-review':'public',published:published.map(a=>({id:a.id,path:pathFor(a)})),renderedDrafts:review?all.filter(a=>a.status==='draft').map(a=>a.id):[],canonicalOrigin:site.url},null,2));
console.log(`Built ${review?'PRIVATE REVIEW':'PUBLIC'}: ${visible.length} article pages; ${published.length} published feed entries.`);
